### ISSUE TITLE
Docker-Compose Config for ergast-f1-api

### ISSUE THREAD

**Issue by psychemedia** [jcnewell/ergast-f1-api#1]
Hi Chris,

I was wondering whether you have a `docker-compose` config script that can be used to quickly fire up a local *ergast* API server using docker?

If not, I'll try to have a bash at setting one up, eg using s/thing like https://github.com/moyed/docker-compose-lamp-stack/ as a recipe.

I seem to recalling using s/thing like the following as a Dockerfile for creating an *ergast* database server?

```
FROM mysql

RUN sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address=0.0.0.0/" /etc/mysql/my.cnf

RUN apt-get update && apt-get install -y wget && apt-get clean

RUN wget http://ergast.com/downloads/f1db.sql.gz -P /docker-entrypoint-initdb.d
RUN gunzip /docker-entrypoint-initdb.d/f1db.sql.gz
```

**Comment by jcnewell** [comment]
Hi Tony,
No, I don't have one but several people have asked about this. If you could create one and contribute it to this repository that would be really great.

**Comment by psychemedia** [comment]
I had a go at it... https://github.com/jcnewell/ergast-f1-api/pull/2
