### ISSUE TITLE
Latest commit probably missing files

### ISSUE THREAD

**Issue by pesaventofilippo** [jcnewell/ergast-f1-api#12]
I saw the latest commit regards updating to PHP8, but it seems like not all files got pushed.
Only the `SprintResults.inc` file got updated with the new functions, while the other files still use the old `mysql_*` functions.
The `SprintResults.inc` file is also not used anywhere else in the code, and that file uses the `$mysqli` variable, which is not declared or assigned anywhere.

Maybe the other files were left behind?

**Comment by jcnewell** [comment]
Thanks for the warning Filippo - now corrected
